/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.visao;

/**
 *
 * @author vinicius.lazaro
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jRquestao1 = new javax.swing.JRadioButton();
        jRquestao2 = new javax.swing.JRadioButton();
        jRquestao3 = new javax.swing.JRadioButton();
        jRquestao4 = new javax.swing.JRadioButton();
        jRquestao5 = new javax.swing.JRadioButton();
        jBescolha1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLstatus1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jRquestao6 = new javax.swing.JRadioButton();
        jRquestao7 = new javax.swing.JRadioButton();
        jRquestao8 = new javax.swing.JRadioButton();
        jRquestao9 = new javax.swing.JRadioButton();
        jRquestao10 = new javax.swing.JRadioButton();
        jBescolha2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLstatus2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jRquestao11 = new javax.swing.JRadioButton();
        jRquestao12 = new javax.swing.JRadioButton();
        jRquestao13 = new javax.swing.JRadioButton();
        jRquestao14 = new javax.swing.JRadioButton();
        jRquestao15 = new javax.swing.JRadioButton();
        jBescolha3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLstatus3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        buttonGroup1.add(jRquestao1);
        jRquestao1.setText("Java");
        jRquestao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRquestao1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRquestao2);
        jRquestao2.setText("Python");

        buttonGroup1.add(jRquestao3);
        jRquestao3.setText("R");

        buttonGroup1.add(jRquestao4);
        jRquestao4.setText("JavaScript");

        buttonGroup1.add(jRquestao5);
        jRquestao5.setText("C#");

        jBescolha1.setText("escolha");
        jBescolha1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBescolha1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Qual a linguagem mais utilizada na área de dados");

        jLstatus1.setText("jLabel6");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(jRquestao1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jBescolha1)
                        .addGap(98, 98, 98)
                        .addComponent(jLstatus1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRquestao2)
                        .addGap(30, 30, 30)
                        .addComponent(jRquestao3)
                        .addGap(31, 31, 31)
                        .addComponent(jRquestao4)
                        .addGap(38, 38, 38)
                        .addComponent(jRquestao5)
                        .addGap(92, 92, 92))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRquestao2)
                    .addComponent(jRquestao1)
                    .addComponent(jRquestao3)
                    .addComponent(jRquestao4)
                    .addComponent(jRquestao5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBescolha1)
                    .addComponent(jLstatus1))
                .addGap(13, 13, 13))
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));

        buttonGroup2.add(jRquestao6);
        jRquestao6.setText("jRadioButton1");

        buttonGroup2.add(jRquestao7);
        jRquestao7.setText("jRadioButton2");

        buttonGroup2.add(jRquestao8);
        jRquestao8.setText("jRadioButton3");

        buttonGroup2.add(jRquestao9);
        jRquestao9.setText("jRadioButton4");

        buttonGroup2.add(jRquestao10);
        jRquestao10.setText("jRadioButton5");

        jBescolha2.setText("escolha");

        jLstatus2.setText("jLabel5");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBescolha2)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jRquestao6)
                                .addGap(18, 18, 18)
                                .addComponent(jRquestao7)
                                .addGap(18, 18, 18)
                                .addComponent(jRquestao8)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jRquestao9)
                                .addGap(18, 18, 18)
                                .addComponent(jRquestao10))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(jLstatus2))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(jLabel2)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRquestao7)
                    .addComponent(jRquestao6)
                    .addComponent(jRquestao8)
                    .addComponent(jRquestao9)
                    .addComponent(jRquestao10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBescolha2)
                    .addComponent(jLstatus2))
                .addGap(13, 13, 13))
        );

        jPanel5.setBackground(new java.awt.Color(204, 204, 255));

        buttonGroup3.add(jRquestao11);
        jRquestao11.setText("jRadioButton1");

        buttonGroup3.add(jRquestao12);
        jRquestao12.setText("jRadioButton2");

        buttonGroup3.add(jRquestao13);
        jRquestao13.setText("jRadioButton3");

        buttonGroup3.add(jRquestao14);
        jRquestao14.setText("jRadioButton4");

        buttonGroup3.add(jRquestao15);
        jRquestao15.setText("jRadioButton5");

        jBescolha3.setText("escolha");

        jLabel3.setText("QUESTAO");

        jLstatus3.setText("jLabel4");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBescolha3)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jRquestao11)
                                .addGap(18, 18, 18)
                                .addComponent(jRquestao12)
                                .addGap(18, 18, 18)
                                .addComponent(jRquestao13)))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jRquestao14)
                                .addGap(18, 18, 18)
                                .addComponent(jRquestao15))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addComponent(jLstatus3))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(jLabel3)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRquestao12)
                    .addComponent(jRquestao11)
                    .addComponent(jRquestao13)
                    .addComponent(jRquestao14)
                    .addComponent(jRquestao15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBescolha3)
                    .addComponent(jLstatus3))
                .addGap(13, 13, 13))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(178, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRquestao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRquestao1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRquestao1ActionPerformed

    private void jBescolha1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBescolha1ActionPerformed
        // TODO add your handling code here:
        if(jRquestao1.isSelected()){
            jLstatus1.setText("Errou");
        }
        else if(jRquestao2.isSelected()){
            jLstatus1.setText("Acertou");
        }
        else if(jRquestao3.isSelected()){
            jLstatus1.setText("Errou");
        }
        else if(jRquestao4.isSelected()){
            jLstatus1.setText("Errou");
        }
        else if(jRquestao5.isSelected()){
            jLstatus1.setText("Errou");
        }
        else {
            jLstatus1.setText("Inválido");
        }
                   
    }//GEN-LAST:event_jBescolha1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jBescolha1;
    private javax.swing.JButton jBescolha2;
    private javax.swing.JButton jBescolha3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLstatus1;
    private javax.swing.JLabel jLstatus2;
    private javax.swing.JLabel jLstatus3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRquestao1;
    private javax.swing.JRadioButton jRquestao10;
    private javax.swing.JRadioButton jRquestao11;
    private javax.swing.JRadioButton jRquestao12;
    private javax.swing.JRadioButton jRquestao13;
    private javax.swing.JRadioButton jRquestao14;
    private javax.swing.JRadioButton jRquestao15;
    private javax.swing.JRadioButton jRquestao2;
    private javax.swing.JRadioButton jRquestao3;
    private javax.swing.JRadioButton jRquestao4;
    private javax.swing.JRadioButton jRquestao5;
    private javax.swing.JRadioButton jRquestao6;
    private javax.swing.JRadioButton jRquestao7;
    private javax.swing.JRadioButton jRquestao8;
    private javax.swing.JRadioButton jRquestao9;
    // End of variables declaration//GEN-END:variables
}
